name: "🧩 Publish VSCode Extension"

on:
    push:
        branches:
            - main
            - feat/extension
        paths:
            - "extension/dorky-extension/**"

jobs:
    publish:
        name: 🧩 publish extension
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: extension/dorky-extension
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Package
              run: npm run package

            - name: Publish to VS Code Marketplace
              run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}

